spring.application.name=LabVerse

#?CHANGE DB CONFIGURATION TO YOUR DB
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=prm392_labverse;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

#spring.sql.init.mode=always

#JWT
application.domain-name=localhost
application.security.jwt.access-token-secret-key=acc0820320b00969e0670c43a43fa2cb926d4a17dde2dc81f470e29a051a8313
application.security.jwt.access-token-expiration=604800000