spring.application.name=LabVerse

#?CHANGE DB CONFIGURATION TO YOUR DB
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=prm392_labverse;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

#spring.sql.init.mode=always
